version: '3.4'

services:
  metro60.webapi:
    image: ${DOCKER_REGISTRY-}metro60webapi
    build:
      context: .
      dockerfile: src/Metro60.WebApi/Dockerfile

  metro60.functionaltests:
    image: ${DOCKER_REGISTRY-}functionaltests
    build:
      context: .
      dockerfile: tests/Metro60.FunctionalTests/Dockerfile
